### ISSUE TITLE
Update should.js devDependencies to accept version ^7.0.0

### ISSUE THREAD

**Issue by wOvalle** [myndzi/should-eventually#2]
Npm console is always reminding me that should library (by the time of writing 7.0.2) does not satisfy should-eventually dependency.

**Comment by myndzi** [comment]
It also doesn't pass the tests...

**Comment by myndzi** [comment]
I believe should.js has promise methods of its own now, so you shouldn't need this module in conjunction with 7.0

**Comment by myndzi** [comment]
See: https://shouldjs.github.io/#assertion-promise
